-- 01. DATABASE SETUP
CREATE DATABASE IF NOT EXISTS Global_superstore;

SHOW DATABASES;

SELECT CURRENT_DATABASE();

USE DATABASE Global_superstore;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS ANALYTICALS;

SHOW SCHEMAS;

CREATE WAREHOUSE IF NOT EXISTS SUPERSTORE_WH
WITH 
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE SUPERSTORE_WH;

SELECT CURRENT_WAREHOUSE();

USE SCHEMA RAW;

SELECT
    CURRENT_DATABASE(),
    CURRENT_SCHEMA(),
    CURRENT_WAREHOUSE();
