-- 02. FILE FORMAT AND STAGE
USE DATABASE Global_superstore;
USE WAREHOUSE SUPERSTORE_WH;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT RAW.CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', '');

SHOW FILE FORMATS IN SCHEMA RAW;

CREATE OR REPLACE STAGE RAW.SUPERSTORE_STAGE
FILE_FORMAT = RAW.CSV_FORMAT;

SHOW STAGES IN SCHEMA RAW;

LIST @RAW.SUPERSTORE_STAGE;

-- Inspect staged data
SELECT
    $1 AS ROW_ID,
    $2 AS ORDER_ID,
    $3 AS ORDER_DATE,
    $4 AS SHIP_DATE,
    $5 AS SHIP_MODE
FROM @RAW.SUPERSTORE_STAGE
(FILE_FORMAT => RAW.CSV_FORMAT)
LIMIT 10;

SELECT
    $1 AS ROW_ID,
    $2 AS ORDER_ID,
    $3::VARCHAR AS ORDER_DATE_RAW,
    $4::VARCHAR AS SHIP_DATE_RAW
FROM @RAW.SUPERSTORE_STAGE
(FILE_FORMAT => RAW.CSV_FORMAT)
LIMIT 20;

DESC FILE FORMAT RAW.CSV_FORMAT;

-- Optional stage maintenance / investigation
-- REMOVE @RAW.SUPERSTORE_STAGE/Global_Superstore_cleaned.csv;
