-- 07. SCD TYPE 1
USE DATABASE Global_superstore;
USE WAREHOUSE SUPERSTORE_WH;
USE SCHEMA ANALYTICALS;

SELECT
    COUNT(*) AS TOTAL_CUSTOMERS,
    COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS
FROM DIM_CUSTOMER;

SELECT * FROM DIM_CUSTOMER LIMIT 20;

SELECT
    CUSTOMER_KEY,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    SEGMENT
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 'RH-9555';

-- Direct SCD Type 1 update
UPDATE DIM_CUSTOMER
SET SEGMENT = 'Corporate'
WHERE CUSTOMER_ID = 'RH-9555';

SELECT
    CUSTOMER_ID,
    COUNT(*) AS TOTAL
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 'RH-9555'
GROUP BY CUSTOMER_ID;

-- Source table for MERGE testing
CREATE OR REPLACE TEMP TABLE CUSTOMER_UPDATE(
    CUSTOMER_ID VARCHAR,
    CUSTOMER_NAME VARCHAR,
    SEGMENT VARCHAR
);

INSERT INTO CUSTOMER_UPDATE
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    SEGMENT
)
VALUES
(
    'RH-9555',
    'Ritsa Hightower',
    'Consumer'
);

-- SCD Type 1 MERGE
MERGE INTO ANALYTICALS.DIM_CUSTOMER AS TARGET
USING CUSTOMER_UPDATE AS SOURCE
ON TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID
WHEN MATCHED THEN
    UPDATE SET
        TARGET.CUSTOMER_NAME = SOURCE.CUSTOMER_NAME,
        TARGET.SEGMENT = SOURCE.SEGMENT
WHEN NOT MATCHED THEN
    INSERT(
        CUSTOMER_ID,
        CUSTOMER_NAME,
        SEGMENT
    )
    VALUES(
        SOURCE.CUSTOMER_ID,
        SOURCE.CUSTOMER_NAME,
        SOURCE.SEGMENT
);

SELECT *
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 'RH-9555';

-- Test a new customer
INSERT INTO CUSTOMER_UPDATE(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    SEGMENT
)
VALUES
(
    'HSR-1234',
    'Dinesh',
    'Reviewer'
);

MERGE INTO ANALYTICALS.DIM_CUSTOMER AS TARGET
USING CUSTOMER_UPDATE AS SOURCE
ON TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID
WHEN MATCHED THEN
    UPDATE SET
        TARGET.CUSTOMER_NAME = SOURCE.CUSTOMER_NAME,
        TARGET.SEGMENT = SOURCE.SEGMENT
WHEN NOT MATCHED THEN
    INSERT(CUSTOMER_ID, CUSTOMER_NAME, SEGMENT)
    VALUES(SOURCE.CUSTOMER_ID, SOURCE.CUSTOMER_NAME, SOURCE.SEGMENT);

SELECT * FROM DIM_CUSTOMER WHERE CUSTOMER_ID = 'HSR-1234';

SELECT COUNT(*) AS TOTAL_ROWS FROM DIM_CUSTOMER;
SELECT COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS FROM DIM_CUSTOMER;
