-- 08. SCD TYPE 2
USE DATABASE Global_superstore;
USE WAREHOUSE SUPERSTORE_WH;
USE SCHEMA ANALYTICALS;

CREATE OR REPLACE TABLE DIM_CUSTOMER_SCD2
(
    CUSTOMER_KEY INT AUTOINCREMENT,
    CUSTOMER_ID VARCHAR,
    CUSTOMER_NAME VARCHAR,
    SEGMENT VARCHAR,
    STAR_DATE DATE,
    END_DATE DATE,
    IS_CURRENT BOOLEAN
);

DESCRIBE TABLE DIM_CUSTOMER_SCD2;

-- Initial load
INSERT INTO DIM_CUSTOMER_SCD2(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    SEGMENT,
    STAR_DATE,
    END_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    SEGMENT,
    CURRENT_DATE(),
    NULL,
    TRUE
FROM ANALYTICALS.DIM_CUSTOMER;

SELECT COUNT(*) AS TOTAL_ROWS
FROM DIM_CUSTOMER_SCD2;

SELECT COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS
FROM DIM_CUSTOMER_SCD2;

-- Manual SCD2 test source
CREATE OR REPLACE TEMP TABLE CUSTOMER_SCD2(
    CUSTOMER_ID VARCHAR,
    CUSTOMER_NAME VARCHAR,
    SEGMENT VARCHAR
);

INSERT INTO CUSTOMER_SCD2(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    SEGMENT
)
VALUES (
    'LB-16795',
    'Laurel Beltran',
    'Corporate'
);

-- Compare old and new values
SELECT
    T.CUSTOMER_ID,
    T.SEGMENT AS OLD_SEGMENT,
    S.SEGMENT AS NEW_SEGMENT
FROM ANALYTICALS.DIM_CUSTOMER_SCD2 AS T
JOIN CUSTOMER_SCD2 AS S
    ON T.CUSTOMER_ID = S.CUSTOMER_ID
WHERE T.IS_CURRENT = TRUE;

-- Close current version
UPDATE ANALYTICALS.DIM_CUSTOMER_SCD2 AS T
SET
    END_DATE = CURRENT_DATE(),
    IS_CURRENT = FALSE
FROM CUSTOMER_SCD2 AS S
WHERE T.CUSTOMER_ID = S.CUSTOMER_ID
  AND T.IS_CURRENT = TRUE
  AND T.SEGMENT <> S.SEGMENT;

-- Insert new version
INSERT INTO ANALYTICALS.DIM_CUSTOMER_SCD2(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    SEGMENT,
    STAR_DATE,
    END_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    SEGMENT,
    CURRENT_DATE(),
    NULL,
    TRUE
FROM CUSTOMER_SCD2;

SELECT *
FROM DIM_CUSTOMER_SCD2
WHERE CUSTOMER_ID = 'LB-16795';
