-- 09. STREAMS
USE DATABASE Global_superstore;
USE WAREHOUSE SUPERSTORE_WH;
USE SCHEMA ANALYTICALS;

SELECT
    CURRENT_DATABASE(),
    CURRENT_WAREHOUSE(),
    CURRENT_SCHEMA();

-- Stream on customer dimension
CREATE OR REPLACE STREAM CUSTOMER_STREAM
ON TABLE DIM_CUSTOMER;

SHOW STREAMS;
DESC STREAM CUSTOMER_STREAM;

SELECT * FROM DIM_CUSTOMER LIMIT 20;

-- Generate a change
UPDATE DIM_CUSTOMER
SET SEGMENT = 'Corporate'
WHERE CUSTOMER_ID = 'SO-20335';

SELECT * FROM CUSTOMER_STREAM;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    SEGMENT,
    METADATA$ACTION,
    METADATA$ISUPDATE
FROM CUSTOMER_STREAM;

-- Incoming table for SCD2 automation
CREATE OR REPLACE TABLE CUSTOMER_INCOMMING(
    CUSTOMER_ID VARCHAR,
    CUSTOMER_NAME VARCHAR,
    SEGMENT VARCHAR
);

CREATE OR REPLACE STREAM CUSTOMER_INCOMMING_STREAM
ON TABLE CUSTOMER_INCOMMING;

SHOW STREAMS IN SCHEMA ANALYTICALS;
DESC STREAM CUSTOMER_INCOMMING_STREAM;

-- Test incoming record
INSERT INTO CUSTOMER_INCOMMING(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    SEGMENT
)
VALUES(
    'BL-10101',
    'NITHIN',
    'Customer'
);

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    SEGMENT,
    METADATA$ACTION,
    METADATA$ISUPDATE
FROM CUSTOMER_INCOMMING_STREAM;

-- Example existing-customer change
UPDATE CUSTOMER_INCOMMING
SET SEGMENT = 'Corporate'
WHERE CUSTOMER_ID = 'BL-10101';

SELECT * FROM CUSTOMER_INCOMMING_STREAM;
