-- 10. TASKS AND SCD2 AUTOMATION
USE DATABASE Global_superstore;
USE WAREHOUSE SUPERSTORE_WH;
USE SCHEMA ANALYTICALS;

-- Simple task logging example
CREATE OR REPLACE TABLE CUSTOMER_TASK_LOG(
    EXECUTION_TIME TIMESTAMP,
    MESSAGE VARCHAR
);

CREATE OR REPLACE TASK CUSTOMER_TASK
    WAREHOUSE = SUPERSTORE_WH
    SCHEDULE = '1 MINUTE'
AS
    INSERT INTO CUSTOMER_TASK_LOG
    SELECT CURRENT_TIMESTAMP(), 'TASK EXECUTED';

SHOW TASKS;

ALTER TASK CUSTOMER_TASK RESUME;

SELECT *
FROM CUSTOMER_TASK_LOG
ORDER BY EXECUTION_TIME DESC;

ALTER TASK CUSTOMER_TASK SUSPEND;

-- ============================================================
-- SCD2 STREAM PROCESSING PROCEDURE
-- Capture the stream once, then use the captured data for
-- both UPDATE and INSERT.
-- ============================================================

CREATE OR REPLACE PROCEDURE PROCESS_CUST_SCD2()
RETURNS VARCHAR()
LANGUAGE SQL
AS
$$
BEGIN

    -- STEP 1: Capture stream data
    CREATE OR REPLACE TEMPORARY TABLE TEMP_CUSTOMER_STREAM AS
    SELECT
        CUSTOMER_ID,
        CUSTOMER_NAME,
        SEGMENT,
        METADATA$ACTION,
        METADATA$ISUPDATE
    FROM CUSTOMER_INCOMMING_STREAM;

    -- STEP 2: Close the current record
    UPDATE DIM_CUSTOMER_SCD2 T
    SET
        END_DATE = CURRENT_DATE(),
        IS_CURRENT = FALSE
    FROM TEMP_CUSTOMER_STREAM S
    WHERE T.CUSTOMER_ID = S.CUSTOMER_ID
      AND T.IS_CURRENT = TRUE
      AND T.SEGMENT <> S.SEGMENT;

    -- STEP 3: Insert new customers and changed customers
    INSERT INTO DIM_CUSTOMER_SCD2
    (
        CUSTOMER_ID,
        CUSTOMER_NAME,
        SEGMENT,
        STAR_DATE,
        END_DATE,
        IS_CURRENT
    )
    SELECT
        S.CUSTOMER_ID,
        S.CUSTOMER_NAME,
        S.SEGMENT,
        CURRENT_DATE(),
        NULL,
        TRUE
    FROM TEMP_CUSTOMER_STREAM S
    LEFT JOIN DIM_CUSTOMER_SCD2 T
        ON S.CUSTOMER_ID = T.CUSTOMER_ID
       AND T.IS_CURRENT = TRUE
    WHERE T.CUSTOMER_ID IS NULL
       OR T.SEGMENT <> S.SEGMENT;

    RETURN 'SCD 2 PROCESS COMPLETED';

END;
$$;

SHOW PROCEDURES LIKE 'PROCESS_CUST_SCD2';

-- Test procedure manually
CALL PROCESS_CUST_SCD2();

SELECT *
FROM DIM_CUSTOMER_SCD2
WHERE CUSTOMER_ID = 'DB-13060';

-- ============================================================
-- SCD2 AUTOMATION TASK
-- ============================================================

CREATE OR REPLACE TASK CUSTOMER_SCD2_TASK
    WAREHOUSE = SUPERSTORE_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('CUSTOMER_INCOMMING_STREAM')
AS
    CALL PROCESS_CUST_SCD2();

ALTER TASK CUSTOMER_SCD2_TASK RESUME;

SHOW TASKS LIKE 'CUSTOMER_SCD2_TASK';

-- Test automation with a new customer
INSERT INTO CUSTOMER_INCOMMING(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    SEGMENT
)
VALUES(
    'AM-10360',
    'Alice McCarthy',
    'Consumer'
);

-- After the task executes:
SELECT *
FROM DIM_CUSTOMER_SCD2
WHERE CUSTOMER_ID = 'AM-10360';

-- Check task status
SHOW TASKS LIKE 'CUSTOMER_SCD2_TASK';

-- Suspend when finished testing
-- ALTER TASK CUSTOMER_SCD2_TASK SUSPEND;
