CREATE DATABASE Global_superstore;
Show databases;
SELECT CURRENT_DATABASE()
USE DATABASE Global_superstore;
CREATE SCHEMA RAW;
CREATE SCHEMA ANALYTICALS;
SHOW SCHEMAS;
CREATE WAREHOUSE SUPERSTORE_WH
WITH 
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;
USE WAREHOUSE SUPERSTORE_WH;
SELECT CURRENT_WAREHOUSE();
USE SCHEMA RAW;
SELECT
    CURRENT_DATABASE(),
    CURRENT_SCHEMA(),
    CURRENT_WAREHOUSE(); 
CREATE FILE FORMAT RAW.CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', '');
SHOW FILE FORMATS IN SCHEMA RAW;

CREATE STAGE RAW.SUPERSTORE_STAGE
FILE_FORMAT = RAW.CSV_FORMAT;
SHOW STAGES IN SCHEMA RAW;

LIST @RAW.SUPERSTORE_STAGE;

CREATE OR REPLACE TABLE ORDERS_RAW (
    row_id INTEGER,
    order_id VARCHAR,
    order_date DATE,
    ship_date DATE,
    ship_mode VARCHAR,
    customer_id VARCHAR,
    customer_name VARCHAR,
    segment VARCHAR,
    city VARCHAR,
    state VARCHAR,
    country VARCHAR,
    postal_code VARCHAR,
    market VARCHAR,
    region VARCHAR,
    product_id VARCHAR,
    category VARCHAR,
    sub_category VARCHAR,
    product_name VARCHAR,
    sales NUMBER(18,2),
    quantity INTEGER,
    discount NUMBER(10,4),
    profit NUMBER(18,2),
    shipping_cost NUMBER(18,2),
    order_priority VARCHAR
);
SHOW TABLES IN SCHEMA RAW;
DESCRIBE TABLE RAW.ORDERS_RAW;
COPY INTO RAW.ORDERS_RAW 
FROM @RAW.SUPERSTORE_STAGE
FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT)
ON_ERROR = 'CONTINUE';
SELECT * FROM RAW.ORDERS_RAW LIMIT 10;

SELECT COUNT(*) FROM RAW.ORDERS_RAW
WHERE POSTAL_CODE IS NULL;

SELECT MIN(order_date) as earliest_date,
MAX(order_date) as latest_date 
from RAW.ORDERS_RAW

SELECT order_date, COUNT(*) AS row_count
FROM RAW.ORDERS_RAW
GROUP BY order_date
ORDER BY order_date;

DESC TABLE RAW.ORDERS_RAW;

SELECT
    $1 AS ROW_ID,
    $2 AS ORDER_ID,
    $3 AS ORDER_DATE,
    $4 AS SHIP_DATE,
    $5 AS SHIP_MODE
FROM @RAW.SUPERSTORE_STAGE
(FILE_FORMAT => RAW.CSV_FORMAT)
LIMIT 10;

LIST @RAW.SUPERSTORE_STAGE

DESC FILE FORMAT RAW.CSV_FORMAT;

SELECT
    $1 AS ROW_ID,
    $2 AS ORDER_ID,
    $3::VARCHAR AS ORDER_DATE_RAW,
    $4::VARCHAR AS SHIP_DATE_RAW
FROM @RAW.SUPERSTORE_STAGE
(FILE_FORMAT => RAW.CSV_FORMAT)
LIMIT 20;

REMOVE @RAW.SUPERSTORE_STAGE/Global_Superstore_cleaned.csv;

LIST @RAW.SUPERSTORE_STAGE;

SELECT
    $1 AS ROW_ID,
    $2 AS ORDER_ID,
    $3 AS ORDER_DATE,
    $4 AS SHIP_DATE
FROM @RAW.SUPERSTORE_STAGE
(FILE_FORMAT => RAW.CSV_FORMAT)
WHERE $1 = '26341' ;

SELECT
    MIN(TRY_TO_DATE($3)) AS EARLIEST_DATE,
    MAX(TRY_TO_DATE($3)) AS LATEST_DATE
FROM @RAW.SUPERSTORE_STAGE
(FILE_FORMAT => RAW.CSV_FORMAT);

TRUNCATE TABLE RAW.ORDERS_RAW;

COPY INTO RAW.ORDERS_RAW
FROM @RAW.SUPERSTORE_STAGE
FILE_FORMAT = RAW.CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT'

select count(*) from 
RAW.ORDERS_RAW;

SELECT
    COUNT(*) AS invalid_dates
FROM RAW.ORDERS_RAW
WHERE ship_date < order_date;

SELECT COUNT(*) AS MISSING_POSTAL_CODE
FROM RAW.ORDERS_RAW WHERE POSTAL_CODE IS NULL;

SELECT COUNT(*) AS TOTDAL_ROWS,
COUNT(DISTINCT row_id) AS UNIQUE_ROWID
FROM RAW.ORDERS_RAW;

USE SCHEMA ANALYTICALS;
CREATE TABLE DIM_CUSTOMER(
customer_key int autoincrement,
customer_id varchar,
customer_name VARCHAR,
segment VARCHAR
);
INSERT INTO DIM_CUSTOMER(
customer_id,
customer_name,
segment
)
SELECT DISTINCT customer_id,
customer_name,
segment
FROM RAW.ORDERS_RAW 
WHERE customer_id IS NOT NULL;

SELECT * FROM DIM_CUSTOMER
LIMIT 10;

SELECT COUNT(*) AS TOTDAL_ROWS,
COUNT(DISTINCT customer_id) AS UNIQUE_ROWID
FROM DIM_CUSTOMER;



CREATE OR REPLACE TABLE DIM_PRODUCT(
    product_key int autoincrement,
    product_id VARCHAR,
     product_name VARCHAR,
    category VARCHAR,
    sub_category VARCHAR
);
INSERT INTO DIM_PRODUCT(
product_id,
product_name,
category,
sub_category
)
SELECT DISTINCT product_id,
product_name,
category,
sub_category
FROM RAW.ORDERS_RAW 
WHERE product_id IS NOT NULL;

SELECT * FROM DIM_PRODUCT
LIMIT 10;

SELECT COUNT(*) AS TOTDAL_ROWS,
COUNT(DISTINCT product_id) AS UNIQUE_ROWID
FROM DIM_PRODUCT;


CREATE TABLE DIM_LOCATION(
    location_key int autoincrement,
    city VARCHAR,
    state VARCHAR,
    country VARCHAR,
    postal_code VARCHAR,
    market VARCHAR,
    region VARCHAR
);


INSERT INTO DIM_LOCATION(
city,
state,
country,
postal_code,
market,
region
)
SELECT DISTINCT 
city,
state,
country,
postal_code,
market,
region
FROM RAW.ORDERS_RAW;

SELECT * FROM DIM_LOCATION
LIMIT 10;

SELECT COUNT(*) AS TOTDAL_ROWS,
FROM DIM_LOCATION;

CREATE OR REPLACE TABLE DIM_DATE(
date_key int,
full_date Date,
year int,
quarter int,
month int,
month_name varchar,
week int,
day int,
day_name varchar
);

select min(order_date) as min_date,
max(order_date) as max_date
from RAW.ORDERS_RAW;

-- MIN_DATE
-- 2011-01-
-- MAX_DATE
-- 2014-12-31

 
INSERT INTO DIM_DATE 
SELECT TO_NUMBER(TO_CHAR(date_value,'YYYYMMDD')) AS date_key,
date_value AS full_date,
YEAR(date_value) as year,
QUARTER(date_value) as quarter,
MONTH(date_value) as month,
MONTHNAME(date_value) as month_name,
WEEK(date_value) as week,
DAY(date_value) as day,
DAYNAME(date_value) as day_name
FROM (SELECT DATEADD(DAY,SEQ4(),
(SELECT MIN(order_date) FROM RAW.ORDERS_RAW))AS date_value 
FROM TABLE (GENERATOR(ROWCOUNT => 5000 )))

SELECT * FROM DIM_DATE
LIMIT 10;

CREATE OR REPLACE TABLE FACT_SALES
(
sales_key int autoincrement,
row_id int,

customer_key int,
product_key int,
location_key int,
date_key int,

order_id VARCHAR,
ship_mode VARCHAR,
order_priority VARCHAR,

sales NUMBER(18,2),
quantity INTEGER,
discount NUMBER(10,4),
profit NUMBER(18,2),
shipping_cost NUMBER(18,2)

);


INSERT INTO FACT_SALES
(
    row_id,
    customer_key,
    product_key,
    location_key,
    date_key,
    order_id,
    ship_mode,
    order_priority,
    sales,
    quantity,
    discount,
    profit,
    shipping_cost
)
SELECT
    r.row_id,
    c.customer_key,
    p.product_key,
    l.location_key,
    TO_NUMBER(TO_CHAR(r.order_date, 'YYYYMMDD')) AS date_key,
    r.order_id,
    r.ship_mode,
    r.order_priority,
    r.sales,
    r.quantity,
    r.discount,
    r.profit,
    r.shipping_cost
FROM RAW.ORDERS_RAW r

LEFT JOIN DIM_CUSTOMER c
    ON r.customer_id = c.customer_id

LEFT JOIN DIM_PRODUCT p
    ON r.product_id = p.product_id
    AND r.product_name = p.product_name
    AND r.category = p.category
    AND r.sub_category = p.sub_category

LEFT JOIN DIM_LOCATION l
    ON COALESCE(r.city, '') = COALESCE(l.city, '')
    AND COALESCE(r.state, '') = COALESCE(l.state, '')
    AND COALESCE(r.country, '') = COALESCE(l.country, '')
    AND COALESCE(r.postal_code, '') = COALESCE(l.postal_code, '')
    AND COALESCE(r.market, '') = COALESCE(l.market, '')
    AND COALESCE(r.region, '') = COALESCE(l.region, '');

SELECT COUNT(*) FROM FACT_SALES;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT row_id) AS UNIQUE_ROW_IDS
FROM FACT_SALES;

SELECT
    product_id,
    COUNT(*) AS cnt
FROM DIM_PRODUCT
GROUP BY product_id
HAVING COUNT(*) > 1
ORDER BY cnt DESC;

SELECT
    product_id,
    product_name,
    category,
    sub_category
FROM DIM_PRODUCT
WHERE product_id = 'OFF-PA-10004673';

SELECT
    product_id,
    product_name,
    category,
    sub_category,
    COUNT(*) AS row_count
FROM RAW.ORDERS_RAW
WHERE product_id = 'OFF-PA-10004673'
GROUP BY
    product_id,
    product_name,
    category,
    sub_category;

SELECT DISTINCT  product_id,
    product_name,
    category,
    sub_category 
FROM RAW.ORDERS_RAW;


SELECT COUNT(*) AS ALL_PRODUCT,
COUNT(DISTINCT product_id) as actual_product
FROM RAW.ORDERS_RAW;

SELECT * FROM DIM_PRODUCT LIMIT 10;

SELECT COUNT(*) AS ALL_PROD,
COUNT(DISTINCT product_id) as actual_prod
FROM DIM_PRODUCT;

SELECT product_id, 
COUNT(DISTINCT category),
COUNT(DISTINCT sub_category),
COUNT(DISTINCT product_name)
from DIM_PRODUCT
group by product_id
HAVING COUNT(DISTINCT category) >1 OR
COUNT(DISTINCT sub_category)>1 OR
COUNT(DISTINCT product_name)>1;

DROP TABLE DIM_LOCATION;
DROP TABLE DIM_DATE;
DROP TABLE FACT_SALES;

SELECT product_id,count (*) as tot_count
FROM DIM_PRODUCT
GROUP BY product_id
HAVING COUNT(*)>1
ORDER BY tot_count DESC;

SELECT COUNT(*) as tot_rows,
count(DISTINCT product_id) as actual_rows,
count_IF(product_id is NULL) as blank_prod
from DIM_PRODUCT;

SELECT product_id, 
COUNT(*) AS ALL_ROWS,
COUNT(DISTINCT category),
COUNT(DISTINCT sub_category),
COUNT(DISTINCT product_name)
from RAW.ORDERS_RAW
group by product_id
HAVING COUNT(*)>1
ORDER BY ALL_ROWS DESC;

SELECT product_id,
product_name,
category,
sub_category,
count(*) as tot_row 
from RAW.ORDERS_RAW
WHERE product_id = 'OFF-AR-10003651'
group by product_id,
product_name,
category,
sub_category
order by tot_row desc;

SELECT COUNT(*) AS TOT_ROWS
FROM DIM_PRODUCT;


SELECT
    COUNT(*) AS TOT_ROWS,
    COUNT(DISTINCT product_id || '|' || product_name) AS UNIQUE_PRODUCTS
FROM DIM_PRODUCT;

SELECT COUNT(*) AS TOT_ROWS,
COUNT (DISTINCT customer_id) as act_rows
FROM DIM_CUSTOMER;

SELECT COUNT(*) AS TOT_ROWS
FROM DIM_LOCATION;

SELECT COUNT(*) AS TOT_ROWS
FROM DIM_DATE;

SELECT COUNT(*) AS TOT_ROWS,
COUNT (DISTINCT row_id) as act_rows
FROM FACT_SALES;

-- OPERATIONS ON DATE

SELECT COUNT_IF(customer_key IS NULL) as tot_cust,
COUNT_IF(product_key IS NULL) as tot_prod,
COUNT_IF(location_key IS NULL) as tot_loc,
COUNT_IF(date_key IS NULL) as tot_date
from FACT_SALES;

SELECT SUM(sales) as tot_sales,
sum(profit) as tot_profit,
sum(quantity) as tot_quantity
from FACT_SALES;

-- Yearly sales

SELECT
d.year,
sum(f.sales) as tot_sales,
sum(f.profit) as tot_profit
from FACT_SALES f 
join DIM_DATE d
on 
f.date_key = d.date_key
group by d.year
order by d.year;

-- Monthly sales

SELECT
d.year,d.month,d.month_name,
sum(f.sales) as tot_sales,
sum(f.profit) as tot_profit
from FACT_SALES f 
join DIM_DATE d
on 
f.date_key = d.date_key
group by d.year,d.month,d.month_name
order by d.year,d.month;

-- Category  sales (TOP 10)

SELECT
p.category,p.sub_category,p.product_name,
sum(f.sales) as tot_sales,
sum(f.profit) as tot_profit
from FACT_SALES f 
join DIM_PRODUCT p
on 
f.product_key = p.product_key
group by p.category,p.sub_category,p.product_name
order by tot_sales desc
LIMIT 10;

desc TABLE DIM_CUSTOMER;

SELECT * FROM DIM_CUSTOMER
LIMIT 10;

-- TOP CUSTOMERS

SELECT
c.customer_name,c.segment,
sum(f.sales) as tot_sales,
sum(f.profit) as tot_profit
from FACT_SALES f 
join DIM_CUSTOMER c
on 
f.customer_key = c.customer_key
group by c.customer_name,c.segment
order by tot_sales desc
LIMIT 10;

-- Top Regions
SELECT
l.country,l.region,
sum(f.sales) as tot_sales,
sum(f.profit) as tot_profit
from FACT_SALES f 
join DIM_LOCATION l
on 
f.location_key = l.location_key
group by l.country,l.region
order by tot_sales desc;

-- Top Market

SELECT
l.country,l.market,
sum(f.sales) as tot_sales,
sum(f.profit) as tot_profit
from FACT_SALES f 
join DIM_LOCATION l
on 
f.location_key = l.location_key
group by l.country,l.market
order by tot_sales desc;

SELECT CURRENT_ACCOUNT(), CURRENT_REGION();

show current_database();
show current_warehouse();

SELECT CURRENT_USER();

-- SCD (Slow changing dimention)
-- SCD 1

SELECT COUNT(*) AS TOT_CUST,
COUNT(DISTINCT CUSTOMER_ID) AS uni_cust
FROM DIM_CUSTOMER

SELECT * FROM DIM_CUSTOMER
LIMIT 20;

SELECT CUSTOMER_KEY,
CUSTOMER_ID,
CUSTOMER_NAME,
SEGMENT 
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 'RH-9555';

UPDATE ANALYTICALS.DIM_CUSTOMER
SET SEGMENT = 'Corporate'
WHERE CUSTOMER_ID = 'RH-9555';

SELECT 
CUSTOMER_ID, COUNT(*) AS TOT
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 'RH-9555'
GROUP BY CUSTOMER_ID;

CREATE OR REPLACE TEMP TABLE 
CUSTOMER_UPDATE(
CUSTOMER_ID varchar,
CUSTOMER_NAME varchar,
SEGMENT varchar
);
INSERT INTO CUSTOMER_UPDATE
(
CUSTOMER_ID,
CUSTOMER_NAME,
SEGMENT 
) VALUES
(
'RH-9555', 
'Ritsa Hightower',
'Consumer'
);

MERGE INTO ANALYTICALS.DIM_CUSTOMER AS TARGET
USING CUSTOMER_UPDATE AS SOURCE 
ON 
TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID
WHEN MATCHED THEN 
UPDATE SET TARGET.CUSTOMER_NAME = SOURCE.CUSTOMER_NAME,
TARGET.SEGMENT = SOURCE.SEGMENT
WHEN NOT MATCHED THEN
INSERT(
CUSTOMER_ID,
CUSTOMER_NAME,
SEGMENT
) VALUES(
SOURCE.CUSTOMER_ID,
SOURCE.CUSTOMER_NAME,
SOURCE.SEGMENT
);

SELECT * FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 'RH-9555';

INSERT INTO CUSTOMER_UPDATE(
CUSTOMER_ID,
CUSTOMER_NAME,
SEGMENT 
) VALUES
(
'HSR-1234', 
'Dinesh',
'Reviewer'
);

SELECT * FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 'HSR-1234';

SELECT * FROM DIM_CUSTOMER
LIMIT 10;

SELECT COUNT(*) AS TOT FROM DIM_CUSTOMER;

SELECT COUNT(DISTINCT CUSTOMER_ID) AS UNI_CUST
FROM DIM_CUSTOMER;

-- SCD TYPE 2

CREATE OR REPLACE TABLE ANALYTICALS.DIM_CUSTOMER_SCD2
(
CUSTOMER_KEY INT AUTOINCREMENT,
CUSTOMER_ID varchar,
CUSTOMER_NAME varchar,
SEGMENT varchar,
STAR_DATE DATE,
END_DATE DATE,
IS_CURRENT BOOLEAN
);
DESCRIBE TABLE DIM_CUSTOMER_SCD2;
INSERT INTO DIM_CUSTOMER_SCD2(
CUSTOMER_ID,
CUSTOMER_NAME,
SEGMENT,
STAR_DATE,
END_DATE,
IS_CURRENT
) 
SELECT CUSTOMER_ID,
CUSTOMER_NAME,
SEGMENT,
CURRENT_DATE(),
NULL,TRUE
FROM ANALYTICALS.DIM_CUSTOMER;

SELECT COUNT(*) AS TOT
FROM DIM_CUSTOMER_SCD2;

SELECT COUNT(DISTINCT CUSTOMER_ID) AS UNI
FROM DIM_CUSTOMER_SCD2;

SELECT * FROM DIM_CUSTOMER_SCD2
WHERE CUSTOMER_ID = 'LB-16795';

CREATE OR REPLACE TEMP TABLE CUSTOMER_SCD2(
CUSTOMER_ID  VARCHAR,
CUSTOMER_NAME VARCHAR,
SEGMENT VARCHAR
);
INSERT INTO CUSTOMER_SCD2(
CUSTOMER_ID,
CUSTOMER_NAME,
SEGMENT 
) VALUES (
'LB-16795',
'Laurel Beltran',
'Corporate'
);
SELECT * FROM CUSTOMER_SCD2
WHERE CUSTOMER_ID = 'LB-16795';

SELECT T.CUSTOMER_ID,
T.SEGMENT AS OLD_SEGMENT,
S.SEGMENT AS NEW_SEGMENT
FROM ANALYTICALS.DIM_CUSTOMER_SCD2
AS T 
JOIN
CUSTOMER_SCD2 AS S 
ON
T.CUSTOMER_ID = S.CUSTOMER_ID
WHERE 
T.IS_CURRENT = TRUE;

UPDATE ANALYTICALS.DIM_CUSTOMER_SCD2 AS T
SET END_DATE = CURRENT_DATE(),
IS_CURRENT = FALSE
FROM CUSTOMER_SCD2 AS S
WHERE T.CUSTOMER_ID = S.CUSTOMER_ID
AND T.IS_CURRENT = TRUE
AND T.SEGMENT <> S.SEGMENT;

INSERT INTO ANALYTICALS.DIM_CUSTOMER_SCD2(
CUSTOMER_ID,
CUSTOMER_NAME,
SEGMENT,
STAR_DATE,
END_DATE,
IS_CURRENT
) SELECT CUSTOMER_ID,
CUSTOMER_NAME,
SEGMENT,
CURRENT_DATE(),
NULL,TRUE 
FROM CUSTOMER_SCD2

SELECT * FROM DIM_CUSTOMER_SCD2
WHERE CUSTOMER_ID ='LB-16795';

-- Streams 

SELECT
CURRENT_DATABASE(),
CURRENT_WAREHOUSE(),
CURRENT_SCHEMA();

CREATE OR REPLACE STREAM CUSTOMER_STREAM
ON TABLE DIM_CUSTOMER;

SHOW STREAMS;

DESC STREAM CUSTOMER_STREAM;

SELECT * FROM DIM_CUSTOMER
LIMIT 20;

UPDATE DIM_CUSTOMER
SET SEGMENT = 'Corporate'
WHERE CUSTOMER_ID = 'SO-20335';

SELECT * FROM CUSTOMER_STREAM;

SELECT CUSTOMER_ID,
CUSTOMER_NAME,
SEGMENT,
METADATA$ACTION,
METADATA$ISUPDATE
FROM CUSTOMER_STREAM;

--Task

CREATE OR REPLACE TABLE CUSTOMER_TASK_LOG(
EXECUTION_TIME TIMESTAMP,
MESSAGE VARCHAR
);

CREATE OR REPLACE TASK CUSTOMER_TASK
WAREHOUSE = SUPERSTORE_WH
SCHEDULE = '1 MINUTE' AS INSERT INTO CUSTOMER_TASK_LOG
SELECT CURRENT_TIMESTAMP(),'TASK EXECUTED'

SELECT * FROM CUSTOMER_TASK_LOG;

SHOW TASKS;

ALTER TASK CUSTOMER_TASK RESUME; 

SELECT * FROM CUSTOMER_TASK_LOG
ORDER BY EXECUTION_TIME DESC;

ALTER TASK CUSTOMER_TASK suspend;

--Task automation

SHOW TABLES IN SCHEMA ANALYTICALS;

SELECT * FROM DIM_CUSTOMER_SCD2 
WHERE CUSTOMER_ID = 'SO-20335';

SELECT COUNT(*) AS TOT,
COUNT(DISTINCT CUSTOMER_ID) AS UNIQ
FROM DIM_CUSTOMER;

SELECT * FROM CUSTOMER_STREAM;

CREATE OR REPLACE TABLE CUSTOMER_INCOMMING(
CUSTOMER_ID VARCHAR,
CUSTOMER_NAME VARCHAR,
SEGMENT VARCHAR
);

CREATE OR REPLACE STREAM CUSTOMER_INCOMMING_STREAM
ON TABLE CUSTOMER_INCOMMING;

SHOW STREAMS IN SCHEMA ANALYTICALS;
DESC STREAM CUSTOMER_INCOMMING_STREAM;

SELECT * FROM CUSTOMER_INCOMMING;

SELECT * FROM DIM_CUSTOMER_SCD2

SELECT COUNT(*) AS TOT ,
COUNT(DISTINCT CUSTOMER_ID) AS UNIQ
FROM DIM_CUSTOMER_SCD2;

SELECT * FROM DIM_CUSTOMER_SCD2
WHERE CUSTOMER_ID = 'LB-16795';

SELECT * FROM CUSTOMER_STREAM;

SELECT CUSTOMER_ID,
COUNT(*) AS TOT
FROM DIM_CUSTOMER_SCD2
GROUP BY CUSTOMER_ID
HAVING COUNT(*)>1;

SELECT CUSTOMER_KEY,
CUSTOMER_ID,
CUSTOMER_NAME,
SEGMENT,
STAR_DATE,
END_DATE,
IS_CURRENT
FROM DIM_CUSTOMER_SCD2
WHERE CUSTOMER_ID = 'LB-16795';

INSERT INTO CUSTOMER_INCOMMING(
CUSTOMER_ID,
CUSTOMER_NAME,
SEGMENT
) VALUES(
'BL-10101',
'NITHIN',
'Customer'
);

SELECT CUSTOMER_ID,
CUSTOMER_NAME,
SEGMENT,
METADATA$ACTION,
METADATA$ISUPDATE
FROM CUSTOMER_INCOMMING_STREAM;

UPDATE DIM_CUSTOMER_SCD2 T 
SET END_DATE = CURRENT_DATE(),
IS_CURRENT = FALSE
FROM CUSTOMER_INCOMMING_STREAM S
WHERE T.CUSTOMER_ID = S.CUSTOMER_ID AND
T.IS_CURRENT = TRUE AND
T.SEGMENT <> S.SEGMENT;

INSERT INTO DIM_CUSTOMER_SCD2(
CUSTOMER_ID,
CUSTOMER_NAME,
SEGMENT,
STAR_DATE,
END_DATE,
IS_CURRENT
) SELECT
CUSTOMER_ID,
CUSTOMER_NAME,
SEGMENT,
CURRENT_DATE(),
NULL,
TRUE FROM CUSTOMER_INCOMMING_STREAM

UPDATE CUSTOMER_INCOMMING
SET SEGMENT = 'Corporate' 
WHERE CUSTOMER_ID = 'BL-10101';

SELECT * FROM CUSTOMER_INCOMMING_STREAM;

SELECT * FROM DIM_CUSTOMER_SCD2
WHERE CUSTOMER_ID = 'DB-13060';

INSERT INTO CUSTOMER_INCOMMING(
CUSTOMER_ID,
CUSTOMER_NAME,
SEGMENT
) VALUES(
'DB-13060',
'Dave Brooks',
'Corporate'
);

SELECT * FROM CUSTOMER_INCOMMING_STREAM;

CREATE OR REPLACE TEMP TABLE STREAM_BACKUP
AS SELECT * FROM CUSTOMER_INCOMMING_STREAM;

CREATE OR REPLACE TEMP TABLE CONSUME AS SELECT
CUSTOMER_ID,
CUSTOMER_NAME,
SEGMENT
FROM CUSTOMER_INCOMMING_STREAM;

INSERT INTO CONSUME
SELECT
CUSTOMER_ID,
CUSTOMER_NAME,
SEGMENT
FROM CUSTOMER_INCOMMING_STREAM;

SELECT * FROM CUSTOMER_INCOMMING_STREAM;

CREATE OR REPLACE PROCEDURE PROCESS_CUST_SCD2()
RETURNS VARCHAR()
LANGUAGE SQL
AS
$$
BEGIN

    -- STEP 1: Capture stream data
    CREATE OR REPLACE TEMPORARY TABLE TEMP_CUSTOMER_STREAM AS
    SELECT
        CUSTOMER_ID,
        CUSTOMER_NAME,
        SEGMENT,
        METADATA$ACTION,
        METADATA$ISUPDATE
    FROM CUSTOMER_INCOMMING_STREAM;


    -- STEP 2: Close the current record
    UPDATE DIM_CUSTOMER_SCD2 T
    SET
        END_DATE = CURRENT_DATE(),
        IS_CURRENT = FALSE
    FROM TEMP_CUSTOMER_STREAM S
    WHERE T.CUSTOMER_ID = S.CUSTOMER_ID
      AND T.IS_CURRENT = TRUE
      AND T.SEGMENT <> S.SEGMENT;


    -- STEP 3: Insert new customers and changed customers
    INSERT INTO DIM_CUSTOMER_SCD2
    (
        CUSTOMER_ID,
        CUSTOMER_NAME,
        SEGMENT,
        STAR_DATE,
        END_DATE,
        IS_CURRENT
    )
    SELECT
        S.CUSTOMER_ID,
        S.CUSTOMER_NAME,
        S.SEGMENT,
        CURRENT_DATE(),
        NULL,
        TRUE
    FROM TEMP_CUSTOMER_STREAM S
    LEFT JOIN DIM_CUSTOMER_SCD2 T
        ON S.CUSTOMER_ID = T.CUSTOMER_ID
       AND T.IS_CURRENT = TRUE
    WHERE T.CUSTOMER_ID IS NULL
       OR T.SEGMENT <> S.SEGMENT;


    RETURN 'SCD 2 PROCESS COMPLETED';

END;
$$;

SHOW PROCEDURES LIKE 'PROCESS_CUST_SCD2';

CALL PROCESS_CUST_SCD2();

SELECT * FROM DIM_CUSTOMER_SCD2
WHERE CUSTOMER_ID = 'DB-13060';

SELECT * FROM CUSTOMER_INCOMMING_STREAM

SHOW STREAMS;

SELECT * FROM CUSTOMER_STREAM;

SHOW TASKS;

CREATE OR REPLACE TASK CUSTOMER_SCD2_TASK
WAREHOUSE = SUPERSTORE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('CUSTOMER_INCOMMING_STREAM')AS
CALL PROCESS_CUST_SCD2();

ALTER TASK CUSTOMER_SCD2_TASK RESUME;

SHOW TASKS LIKE 'CUSTOMER_SCD2_TASK';

SELECT * FROM DIM_CUSTOMER_SCD2
LIMIT 25;

INSERT INTO CUSTOMER_INCOMMING(
CUSTOMER_ID,
CUSTOMER_NAME,
SEGMENT
) VALUES(
'AM-10360',
'Alice McCarthy',
'Consumer'
);


SELECT * FROM DIM_CUSTOMER_SCD2
WHERE CUSTOMER_ID = 'AM-10360';

